<?php

return [
    'access' => [
        'category-list' => 'category_list',
        'category-edit' => 'category_edit',
        'category-add' => 'category_add',
        'category-delete' => 'category_delete',
        'product-list' => 'product_list',
        'product-edit' => 'product_edit',
        'product-add' => 'product_add',
        'product-delete' => 'product_delete',
        'user-list' => 'user_list',
        'user-edit' => 'user_edit',
        'user-add' => 'user_add',
        'user-delete' => 'user_delete',
        'order-list' => 'order_list',
        'order-edit' => 'order_edit',
        'order-add' => 'order_add',
        'order-delete' => 'order_delete',
        'role-list' => 'role_list',
        'role-edit' => 'role_edit',
        'role-add' => 'role_add',
        'role-delete' => 'role_delete',
        'permission-list' => 'permission_list',
        'permission-edit' => 'permission_edit',
        'permission-add' => 'permission_add',
        'permission-delete' => 'permission_delete',
        'setting-list' => 'setting_list',
        'setting-edit' => 'setting_edit',
        'setting-add' => 'setting_add',
        'setting-delete' => 'setting_delete',
        'slider-list' => 'slider_list',
        'slider-edit' => 'slider_edit',
        'slider-add' => 'slider_add',
        'slider-delete' => 'slider_delete',
        'attribute-list' => 'attribute_list',
        'attribute-edit' => 'attribute_edit',
        'attribute-add' => 'attribute_add',
        'attribute-delete' => 'attribute_delete',
        'payment-list' => 'payment_list',
        'payment-edit' => 'payment_edit',
        'payment-add' => 'payment_add',
        'payment-delete' => 'payment_delete',
        'orderStatus-list' => 'orderStatus_list',
        'orderStatus-edit' => 'orderStatus_edit',
        'orderStatus-add' => 'orderStatus_add',
        'orderStatus-delete' => 'orderStatus_delete',
        'voucher-list' => 'voucher_list',
        'voucher-edit' => 'voucher_edit',
        'voucher-add' => 'voucher_add',
        'voucher-delete' => 'voucher_delete',
        'infrastructureCity-list' => 'infrastructureCity_list',
        'infrastructureCity-edit' => 'infrastructureCity_edit',
        'infrastructureCity-add' => 'infrastructureCity_add',
        'infrastructureCity-delete' => 'infrastructureCity_delete',
        'infrastructureWard-list' => 'infrastructureWard_list',
        'infrastructureWard-edit' => 'infrastructureWard_edit',
        'infrastructureWard-add' => 'infrastructureWard_add',
        'infrastructureWard-delete' => 'infrastructureWard_delete',
        'infrastructureDistrict-list' => 'infrastructureDistrict_list',
        'infrastructureDistrict-edit' => 'infrastructureDistrict_edit',
        'infrastructureDistrict-add' => 'infrastructureDistrict_add',
        'infrastructureDistrict-delete' => 'infrastructureDistrict_delete',
        'saleStatistic-list' => 'saleStatistic_list',
        'saleStatistic-edit' => 'saleStatistic_edit',
        'saleStatistic-add' => 'saleStatistic_add',
        'saleStatistic-delete' => 'saleStatistic_delete',
        'inventory-list' => 'inventory_list',
        'inventory-edit' => 'inventory_edit',
        'inventory-add' => 'inventory_add',
        'inventory-delete' => 'inventory_delete',
        'media-list' => 'media_list',
        'media-edit' => 'media_edit',
        'media-add' => 'media_add',
        'media-delete' => 'media_delete',
        'seo-list' => 'seo_list',
        'seo-edit' => 'seo_edit',
        'seo-add' => 'seo_add',
        'seo-delete' => 'seo_delete',
        'rating-list' => 'rating_list',
        'rating-edit' => 'rating_edit',
        'rating-add' => 'rating_add',
        'rating-delete' => 'rating_delete',
        'flashSale-list' => 'flashSale_list',
        'flashSale-edit' => 'flashSale_edit',
        'flashSale-add' => 'flashSale_add',
        'flashSale-delete' => 'flashSale_delete',
    ],
    'table_modules' => [
        'category',
        'product',
        'user',
        'order',
        'role',
        'permission',
        'setting',
        'slider',
        'attribute',
        'payment',
        'orderStatus',
        'voucher',
        'infrastructureCity',
        'infrastructureWard',
        'infrastructureDistrict',
        'saleStatistic',
        'inventory',
        'media',
        'seo',
        'rating',
        'flashSale',
    ],
    'action' => [
        'list',
        'add',
        'edit',
        'delete',
    ],
];
