name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/SHOPBANHANG

            git pull origin main

            composer install --no-dev --optimize-autoloader


            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx
