name: Deploy Laravel (Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /var/www/SHOPBANHANG

          git pull origin main

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          sudo systemctl restart php8.1-fpm
          sudo systemctl restart nginx
